### ISSUE TITLE
Fail if current user is not superuser

### ISSUE THREAD

**Issue by mufid** [mufid/db-refresher#1]
```
==> default: rake aborted!
==> default: PG::ConnectionBad: FATAL:  password authentication failed for user "posfeuser"
==> default: FATAL:  password authentication failed for user "posfeuser"
==> default: /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize'
==> default: /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `new'
==> default: /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
==> default: /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
==> default: /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
==> default: /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
==> default: /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
==> default: /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
==> default: /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
==> default: /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
==> default: /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
==> default: /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
==> default: /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
==> default: /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
==> default: /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.6/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
==> default: /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.6/lib/active_record/connection_handling.rb:87:in `connection'
==> default: /home/vagrant/.rvm/gems/ruby-2.3.1/gems/refresher-0.1.0/lib/tasks/db_refresher.rake:10:in `block (2 levels) in <top (required)>'
==> default: /home/vagrant/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
==> default: /home/vagrant/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
==> default: Tasks: TOP => refresh_pg => db_refresher => db_refresher:refresh
==> default: (See full trace by running task with --trace)
=
```

**Comment by mufid** [comment]
Commit on progress. Although it fixed current issue, the error is still subtle. "password authentication failed" may means other than "user not found." Hence, a better solution is just create current user first, then make sure the error is only "NoDatabaseError".
